### ISSUE TITLE
upgrade to rand 0.7?

### ISSUE THREAD

**Issue by Silur** [dalek-cryptography/ed25519-dalek#89]
the rand API changed a bit since 0.6 (there's no `OsRng::new()` anymore). Fortunately nothing breaks if you simply switch the version in Cargo.toml :)

**Comment by derReineke** [comment]
I second this. Currently I am also getting the error when trying to compile. In ed25519.rs on line 974: use rand::thread_rng; I am getting the error "no 'thread_rng' in the root". I have a feeling this is due to the rand crate version.

**Comment by hdevalence** [comment]
This crate depends on `rand` version `0.6`, which includes `thread_rng`.  That error suggests that Cargo is resolving `rand` to a version which is not `0.6`.  Can you put the output of `cargo tree` in a gist and link it here?

**Comment by hdevalence** [comment]
I can't tell what the problem is without having more information about what versions of all the `rand` crates are being used, but this seems like other crates also have the same problem, and my suspicion is that the `rand` crate has broken semver, again.

https://github.com/rust-random/rand/issues/842

**Comment by derReineke** [comment]
Here is the gist:
https://gist.github.com/derReineke/fdf29109dd4ec7b64372e9e1b2f3119e

**Comment by Dhole** [comment]
I have also encountered an issue with the latest rand (0.7).  It seems that the following example doesn't work with rand 0.7:
```rust
extern crate rand;
extern crate ed25519_dalek;

use rand::Rng;
use rand::rngs::OsRng;
use ed25519_dalek::Keypair;
use ed25519_dalek::Signature;

let mut csprng: OsRng = OsRng::new().unwrap();
let keypair: Keypair = Keypair::generate(&mut csprng);
```
With the following error:
```
error[E0277]: the trait bound `rand::rngs::OsRng: rand_core::CryptoRng` is not satisfied
  --> examples/ed25519.rs:12:19
   |
12 |     let keypair = Keypair::generate(&mut csprng);
   |                   ^^^^^^^^^^^^^^^^^ the trait `rand_core::CryptoRng` is not implemented for `rand::rngs::OsRng`
   |
   = note: required by `ed25519_dalek::Keypair::generate`
```

It seems that the error appears because `Keypair::generate` expects the trait `rand::CryptoRng` while `rand::rngs::OsRng` in rand 0.7 implements the trait `rand_core::CryptoRng`.
Setting rand to version 0.6 in `Cargo.toml` solved the issue, but it would be nice to update `ed25519-dalek` to rand 0.7.

**Comment by Silur** [comment]
@Dhole seems like there's is [no intention](https://github.com/dalek-cryptography/curve25519-dalek/pull/263#issuecomment-510988504) to resolve this because of semver reasons. Best temporal solution is to fork or include the crate locally for a while.

**Comment by isislovecruft** [comment]
Hi! Unfortunately, `ed25519-dalek` cannot update until `curve25519-dalek` does. Since the latter is a breaking change, it requires releasing a 2.0.0, which we have no plans to do in the short- to medium-term future.

**Comment by clintfred** [comment]
In case anyone is look at this in the future, it looks like rand 0.7 is used https://github.com/dalek-cryptography/ed25519-dalek/releases/tag/1.0.0-pre.3
